### ISSUE TITLE
아이콘을 돈돈이 8비트 버전으로 바꾸는 건 어떨까요?

### ISSUE THREAD

**Issue by senaaac** [UYEONG/lezhin-sidebar#1]
![2017-08-09 11 03 07](https://user-images.githubusercontent.com/24623626/29102206-6fb5e1dc-7cf2-11e7-9a63-e5a9aa2dc284.png)

위키에서 짤 붙여봅니다. 디자인팀에서 이전에 만들었던 것이 있으니 아마도;;; 금방 주실듯요 ㅋㅋ

**Comment by UYEONG** [comment]
8비트로 하는건 웨일 기본 ICON과 어울리지가 않을 거 같네요.
8비트 느낌만 없는 돈독이로 바꿔보겠습니다.

<img width="40" alt="2017-08-09 1 50 20" src="https://user-images.githubusercontent.com/1321707/29105586-bcec3598-7d09-11e7-8adc-ddaac7440cb2.png">

**Comment by UYEONG** [comment]
@senaaac 님 전신을 아이콘화 하는건 힘들어서 아래처럼 해봤는데 어떤가요?

<img width="938" alt="2017-08-09 3 22 48" src="https://user-images.githubusercontent.com/1321707/29107782-c6cae606-7d16-11e7-9a29-31b9f4fe1419.png">
<img width="507" alt="2017-08-09 3 22 54" src="https://user-images.githubusercontent.com/1321707/29107783-c6d0dd0e-7d16-11e7-8749-f7c9cc49596a.png">
<img width="39" alt="2017-08-09 3 22 59" src="https://user-images.githubusercontent.com/1321707/29107784-c6fb3270-7d16-11e7-8de5-e8e7723c886b.png">

**Comment by UYEONG** [comment]
@senaaac 의견 주셔서 고맙습니다!
